version: '3.3'
services:
  mysqldb:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: restaurantoptimize
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3308:3306
    volumes:
      - restaurantoptimize:/var/lib/mysql
volumes:
  restaurantoptimize: